[package]
name = "tsp"
version = "0.2.9"
authors = ["Adrian Brink <adrian@brink-holdings.com>", "Jackson Lewis <st.japa6@gmail.com>"]
license = "MIT/Apache-2.0"
description = "An implementation of the TSP protocol used by Tendermint Core. Allows the building of COSMOS apps in Rust."
homepage = "https://tendermint.com/docs/guides/app-development"
repository = "https://github.com/tendermint/rust-tsp"
documentation = "https://docs.rs/tsp/0.2.3/tsp/"
keywords = ["tsp", "tendermint", "cosmos", "blockchain", "proof-of-stake"]
categories = ["encoding"]
readme = "README.md"
include = ["src/**/*", "Cargo.toml"]

[dependencies]
byteorder = "1.0"
bytes = "0.4"
futures = "0.1.14"
futures-cpupool = "0.1.5"
protobuf = "2.0.1"
tls-api = "0.*"
tokio-core = "0.1"
tokio-io = "0.1"
tokio-proto = "0.1"
tokio-service = "0.1"
integer-encoding = "1.0.5"

[build-dependencies]
protoc = "1.4.1"
protobuf-codegen-pure = "2.0.1"
